// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/vex-js/vex-js.d.ts
declare namespace vex {

  interface ICSSAttributes {
    [property: string]: string | number;
  }

  interface IVexOptions {
    afterClose?: (() => void);
    afterOpen?: ((vexContent: JQuery) => void);
    content?: string;
    showCloseButton?: boolean;
    escapeButtonCloses?: boolean;
    overlayClosesOnClick?: boolean;
    appendLocation?: HTMLElement | JQuery | string;
    className?: string;
    css?: ICSSAttributes;
    overlayClassName?: string;
    overlayCSS?: ICSSAttributes;
    contentClassName?: string;
    contentCSS?: ICSSAttributes;
    closeClassName?: string;
    closeCSS?: ICSSAttributes;
  }

  interface Vex {
    dialog : any;
    open(options: IVexOptions): JQuery;
    close(id?: number): boolean;
    closeAll(): boolean;
    closeByID(id: number): boolean;
  }

}

declare module "vex" {
  export = vex;
}

declare var vex: vex.Vex;
